packages:
  - packages/*
  - api
  - docs

allowBuilds:
  '@nestjs/core': false
  '@scarf/scarf': false
  '@swc/core': false
  better-sqlite3: false
  cpu-features: false
  esbuild: true
  msgpackr-extract: false
  protobufjs: false
  sqlite3: false
  ssh2: false

minimumReleaseAgeExclude:
  - '@cqrs-ddd/core@0.5.0'
  - '@cqrs-ddd/mikro-orm@0.5.0'
  - '@cqrs-ddd/pipeline-audit@0.5.0'
  - '@cqrs-ddd/pipeline-cache@0.5.0'
  - '@cqrs-ddd/pipeline-casl@0.5.0'
  - '@cqrs-ddd/pipeline-correlation@0.5.0'
  - '@cqrs-ddd/pipeline-deadletter@0.5.0'
  - '@cqrs-ddd/pipeline-feature-flags@0.5.0'
  - '@cqrs-ddd/pipeline-idempotency@0.5.0'
  - '@cqrs-ddd/pipeline-job-context@0.5.0'
  - '@cqrs-ddd/pipeline-opentelemetry@0.5.0'
  - '@cqrs-ddd/pipeline-rate-limit@0.5.0'
  - '@cqrs-ddd/pipeline-resilience@0.5.0'
  - '@cqrs-ddd/pipeline-tenant@0.5.0'
  - '@cqrs-ddd/pipeline-zod@0.5.0'
  - '@cqrs-ddd/pipeline@0.5.0'
  - '@cqrs-ddd/safe-stringify@0.5.0'
  - '@cqrs-ddd/untyped@0.5.0'
  - '@cqrs-ddd/uuidv7@0.5.0'
  - '@cqrs-ddd/nestjs@0.5.0'

onlyBuiltDependencies:
  - esbuild

peerDependencyRules:
  ignoreMissing:
    - '@keyv/memcache'
    - '@keyv/postgres'
    - '@keyv/redis'
    - '@keyv/sqlite'
