/* Copyright (C) 2026-present Aristotelis — see repository license. */

import { type ICache, isVersionedCache } from '../cache.interface';
import type { ICacheLogger } from '../cache-logger';
import type { CommandRepository } from '../command-repository.abstract';
import {
  type CacheBarrierReason,
  createCacheMutationBarrier,
} from '../helpers/cache-barrier.helper';
import { consoleCacheLogger, safeWarn } from '../helpers/cache-logger.helper';
import { reportMissingCacheProperty } from '../helpers/cache-owner.helper';
import { toCacheSnapshot } from '../helpers/cache-snapshot.helper';
import { isCacheNewer } from '../helpers/cache-version.helper';

const defaultLogger = consoleCacheLogger('CacheDecorator');

function errorMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

/**
 * Evicts one key using the strongest coordination the adapter supports.
 *
 * A {@link IVersionedCache} advances the key revision, which already fences any
 * fill that started before this mutation, so no barrier value is stored: leaving
 * one behind would make the next read hydrate a sentinel instead of a snapshot.
 * Unversioned adapters have no revision to compare, so they receive a
 * {@link CacheMutationBarrier} instead. {@link FromCache} bypasses such adapters,
 * and wherever it meets a barrier it treats it as a miss, never as a snapshot.
 */
async function evictKey(
  cache: ICache<unknown>,
  key: string,
  reason: CacheBarrierReason,
  entity: unknown,
  barrierTtl: number,
): Promise<void> {
  if (isVersionedCache(cache)) {
    await cache.invalidate(key);
    return;
  }

  const barrier = createCacheMutationBarrier(reason, entity);
  await cache.set(key, barrier, { ttl: barrierTtl });
}

/**
 * Options for configuring write-through and eviction caching via {@link Cache}.
 */
export interface CacheOptions<TEntity = unknown> {
  /**
   * Function deriving the cache key to write on success.
   * Pass `null` or omit to skip write-through caching.
   */
  setKey?: ((entity: TEntity) => string) | null;

  /**
   * Function deriving keys to evict when `save()` returns `null` or `undefined` (e.g. deletion).
   */
  deleteKeys?: ((entity: TEntity) => string[]) | null;

  /**
   * Optional secondary keys to evict on every successful save before writing the new entry.
   */
  invalidateKeys?: ((entity: TEntity) => string[]) | null;

  /**
   * Optional time-to-live in milliseconds for the write-through cache entry.
   */
  ttl?: number;

  /**
   * Optional version comparison function for CAS-safe write-through caching.
   * If omitted, defaults to {@link isCacheNewer} which compares `version`, `__gen`, or `updatedAt`.
   * Pass `null` to explicitly disable CAS.
   */
  isNewer?: ((cached: unknown, incoming: unknown) => boolean) | null;

  /**
   * Lifetime in milliseconds of the {@link CacheMutationBarrier} written on
   * deletions and secondary invalidations.
   *
   * A barrier only has to outlive the in-flight reads/writes it guards against,
   * so configure this above the expected maximum repository operation latency.
   * Ignored by {@link IVersionedCache} adapters, which fence concurrent fills by
   * revision instead of by barrier token.
   *
   * @default {@link DEFAULT_BARRIER_TTL_MS}
   */
  barrierTtl?: number;

  /**
   * Receives cache-maintenance warnings. Defaults to `console.warn` with a
   * `[CacheDecorator]` prefix. See {@link ICacheLogger}.
   */
  logger?: ICacheLogger;
}

/**
 * Default barrier lifetime: long enough to outlive an in-flight read or write
 * that started before the mutation, short enough that deleted aggregates do not
 * accumulate keys indefinitely.
 */
export const DEFAULT_BARRIER_TTL_MS = 60_000;

/**
 * Write-through cache decorator for a {@link CommandRepository} `save` method.
 *
 * Provides declarative cache synchronization on mutating database operations:
 * - **Write-through update**: When `save()` resolves with a non-nullish result, the result is cached
 *   under the key generated by `setKey` (after invalidating any secondary keys via `invalidateKeys`).
 * - **Cache eviction on delete**: When `save()` resolves with `null` or `undefined` (e.g. entity deletion),
 *   all keys returned by `deleteKeys` are evicted from the cache.
 * - **Best-effort safety**: Cache write and eviction operations swallow errors internally so that an
 *   already-committed database transaction is never converted into an application error.
 * - **Explicit key derivation**: Requires explicit key derivation functions or options to prevent
 *   unscoped or ambiguous key collisions across multi-tenant boundaries.
 *
 * @example Positional syntax on creation / update
 * ```typescript
 * @Cache<User, UserSnapshot>(
 *   (user) => filterCacheKey(User.aggregateName, { id: user.id }),
 *   null,
 *   (user) => [filterCacheKey(User.aggregateName, { email: user.email })],
 * )
 * async save(user: User): Promise<UserSnapshot> { ... }
 * ```
 *
 * Cache maintenance runs only after the wrapped persistence method succeeds and
 * is best-effort: cache failures are logged rather than converting an already
 * durable write into an application failure. Pair this decorator with
 * `@AcknowledgePersisted` and `@MapPersistenceErrors` in the canonical order.
 *
 * @example Options object syntax on eviction / delete
 * ```typescript
 * @Cache<User, null>({
 *   deleteKeys: (user) => [
 *     filterCacheKey(User.aggregateName, { id: user.id }),
 *     filterCacheKey(User.aggregateName, { email: user.email }),
 *   ],
 * })
 * async save(user: User): Promise<null> { ... }
 * ```
 */
export function Cache<TEntity = unknown, TResult = unknown | null>(
  setKeyOrOptions: ((entity: TEntity) => string) | CacheOptions<TEntity> | null,
  deleteKeysFn?: ((entity: TEntity) => string[]) | null,
  invalidateKeysFn?: ((entity: TEntity) => string[]) | null,
): MethodDecorator {
  const options: CacheOptions<TEntity> =
    typeof setKeyOrOptions === 'function' || setKeyOrOptions === null
      ? {
          setKey: setKeyOrOptions,
          deleteKeys: deleteKeysFn,
          invalidateKeys: invalidateKeysFn,
        }
      : setKeyOrOptions;
  if (!options || typeof options !== 'object') {
    throw new Error(
      '@Cache decorator requires an explicit key derivation function or options object.',
    );
  }

  const resolvedSetKey = options.setKey ?? null;
  const resolvedDeleteKeys = options.deleteKeys ?? null;
  const resolvedInvalidateKeys = options.invalidateKeys ?? null;
  const resolvedTtl = options.ttl;
  const resolvedBarrierTtl = options.barrierTtl ?? DEFAULT_BARRIER_TTL_MS;
  const logger = options.logger ?? defaultLogger;
  const resolvedIsNewer =
    options.isNewer === null ? undefined : (options.isNewer ?? isCacheNewer);

  if (!resolvedSetKey && !resolvedDeleteKeys && !resolvedInvalidateKeys) {
    throw new Error(
      '@Cache decorator requires at least one of setKey, deleteKeys, or invalidateKeys to be specified.',
    );
  }

  return (
    _target: object,
    _propertyKey: string | symbol,
    descriptor: PropertyDescriptor,
  ) => {
    const original = descriptor.value as (
      entity: TEntity,
    ) => Promise<TResult | null>;

    descriptor.value = async function (
      this: CommandRepository<TEntity, unknown | null>,
      entity: TEntity,
    ): Promise<TResult | null> {
      // Observed before persistence so a write-through can tell whether anyone
      // mutated the key while this write was in flight. A versioned adapter has
      // no barrier value to outrank a late snapshot, so the revision it hands
      // out here is what keeps a deleted aggregate from being resurrected.
      let observedKey: string | undefined;
      let observedRevision: string | undefined;
      let observedValue: unknown;

      if (this.cache && resolvedSetKey && isVersionedCache(this.cache)) {
        try {
          observedKey = resolvedSetKey(entity);
          const state = await this.cache.readState(observedKey);
          observedRevision = state.revision;
          observedValue = state.status === 'hit' ? state.value : undefined;
        } catch {
          observedKey = undefined;
          observedRevision = undefined;
        }
      }

      const result = await original.call(this, entity);

      if (!this.cache) {
        reportMissingCacheProperty(this, '@Cache', options.logger);
        return result;
      }

      // Cache maintenance is best-effort: the DB write already succeeded,
      // so a cache failure must not turn a success into an error (which
      // would cause idempotency release-on-error to drop the claim).
      try {
        const deleting = result === null || result === undefined;
        const keysFn = deleting ? resolvedDeleteKeys : resolvedInvalidateKeys;
        if (keysFn) {
          let keys: string[] = [];
          try {
            keys = keysFn(entity) ?? [];
          } catch (err) {
            const keyOption = deleting ? 'deleteKeys' : 'invalidateKeys';
            const operation = deleting ? 'cache eviction' : 'cache maintenance';
            safeWarn(
              logger,
              `Failed resolving ${keyOption} during ${operation}: ${errorMessage(err)}`,
            );
          }
          for (const key of keys) {
            try {
              await evictKey(
                this.cache,
                key,
                deleting ? 'deleted' : 'invalidated',
                entity,
                resolvedBarrierTtl,
              );
            } catch (err) {
              const action = deleting ? 'evicting deletion' : 'invalidating';
              safeWarn(
                logger,
                `Failed ${action} key "${key}": ${errorMessage(err)}`,
              );
            }
          }
        }
        if (deleting) return result;

        if (resolvedSetKey) {
          let setKey: string | undefined;
          try {
            setKey = resolvedSetKey(entity);
          } catch (err) {
            safeWarn(
              logger,
              `Failed resolving setKey during cache maintenance: ${errorMessage(err)}`,
            );
          }
          if (setKey) {
            try {
              const snapshot = toCacheSnapshot(result);

              if (isVersionedCache(this.cache)) {
                if (observedRevision !== undefined && setKey === observedKey) {
                  // Skip the write-through when the snapshot observed before
                  // persistence is already newer; otherwise commit it only if
                  // the revision still matches, so a concurrent mutation wins.
                  if (!resolvedIsNewer?.(observedValue, snapshot)) {
                    await this.cache.tryFill(
                      setKey,
                      observedRevision,
                      snapshot as never,
                      { ttl: resolvedTtl },
                    );
                  }
                } else {
                  // No revision was observed for this key before the write, so
                  // a fill cannot be fenced; drop the pre-write value instead.
                  await this.cache.invalidate(setKey);
                }
              } else {
                await this.cache.set(setKey, snapshot, {
                  ttl: resolvedTtl,
                  isNewer: resolvedIsNewer,
                });
              }
            } catch (err) {
              safeWarn(
                logger,
                `Failed setting cache key "${setKey}": ${errorMessage(err)}`,
              );
            }
          }
        }
      } catch (err) {
        safeWarn(
          logger,
          `Unexpected error during cache maintenance: ${errorMessage(err)}`,
        );
      }

      return result;
    };
  };
}
