/* Copyright (C) 2026-present Aristotelis — see repository license. */

import { Logger } from '@nestjs/common';
import type { CommandRepository } from '../command-repository.abstract';
import { createCacheMutationBarrier } from '../helpers/cache-barrier.helper';
import { toCacheSnapshot } from '../helpers/cache-snapshot.helper';
import { isCacheNewer } from '../helpers/cache-version.helper';

const logger = new Logger('CacheDecorator');

/**
 * Options for configuring write-through and eviction caching via {@link Cache}.
 */
export interface CacheOptions<TEntity = unknown> {
  /**
   * Function deriving the cache key to write on success.
   * Pass `null` or omit to skip write-through caching.
   */
  setKey?: ((entity: TEntity) => string) | null;

  /**
   * Function deriving keys to evict when `save()` returns `null` or `undefined` (e.g. deletion).
   */
  deleteKeys?: ((entity: TEntity) => string[]) | null;

  /**
   * Optional secondary keys to evict on every successful save before writing the new entry.
   */
  invalidateKeys?: ((entity: TEntity) => string[]) | null;

  /**
   * Optional time-to-live in milliseconds for the write-through cache entry.
   */
  ttl?: number;

  /**
   * Optional version comparison function for CAS-safe write-through caching.
   * If omitted, defaults to {@link isCacheNewer} which compares `version`, `__gen`, or `updatedAt`.
   * Pass `null` to explicitly disable CAS.
   */
  isNewer?: ((cached: unknown, incoming: unknown) => boolean) | null;

  /**
   * Lifetime in milliseconds of the {@link CacheMutationBarrier} written on
   * deletions and secondary invalidations.
   *
   * A barrier only has to outlive the in-flight work it guards against, so it is
   * bounded rather than permanent. It previously used `ttl: 0`, which several
   * adapters — including `MemoryCache` — read as "never expires", leaving one
   * immortal key behind for every deleted aggregate.
   *
   * @default {@link DEFAULT_BARRIER_TTL_MS}
   */
  barrierTtl?: number;
}

/**
 * Default barrier lifetime: long enough to outlive an in-flight read or write
 * that started before the mutation, short enough that deleted aggregates do not
 * accumulate keys indefinitely.
 */
export const DEFAULT_BARRIER_TTL_MS = 60_000;

/**
 * Write-through cache decorator for a {@link CommandRepository} `save` method.
 *
 * Provides declarative cache synchronization on mutating database operations:
 * - **Write-through update**: When `save()` resolves with a non-nullish result, the result is cached
 *   under the key generated by `setKey` (after invalidating any secondary keys via `invalidateKeys`).
 * - **Cache eviction on delete**: When `save()` resolves with `null` or `undefined` (e.g. entity deletion),
 *   all keys returned by `deleteKeys` are evicted from the cache.
 * - **Best-effort safety**: Cache write and eviction operations swallow errors internally so that an
 *   already-committed database transaction is never converted into an application error.
 * - **Explicit key derivation**: Requires explicit key derivation functions or options to prevent
 *   unscoped or ambiguous key collisions across multi-tenant boundaries.
 *
 * @example Positional syntax on creation / update
 * ```typescript
 * @Cache<User, UserSnapshot>(
 *   (user) => filterCacheKey(User.aggregateName, { id: user.id }),
 *   null,
 *   (user) => [filterCacheKey(User.aggregateName, { email: user.email })],
 * )
 * async save(user: User): Promise<UserSnapshot> { ... }
 * ```
 *
 * @example Options object syntax on eviction / delete
 * ```typescript
 * @Cache<User, null>({
 *   deleteKeys: (user) => [
 *     filterCacheKey(User.aggregateName, { id: user.id }),
 *     filterCacheKey(User.aggregateName, { email: user.email }),
 *   ],
 * })
 * async save(user: User): Promise<null> { ... }
 * ```
 */
export function Cache<TEntity = unknown, TResult = unknown | null>(
  setKeyOrOptions: ((entity: TEntity) => string) | CacheOptions<TEntity> | null,
  deleteKeysFn?: ((entity: TEntity) => string[]) | null,
  invalidateKeysFn?: ((entity: TEntity) => string[]) | null,
): MethodDecorator {
  let resolvedSetKey: ((entity: TEntity) => string) | null = null;
  let resolvedDeleteKeys: ((entity: TEntity) => string[]) | null = null;
  let resolvedInvalidateKeys: ((entity: TEntity) => string[]) | null = null;
  let resolvedTtl: number | undefined;
  let resolvedBarrierTtl: number = DEFAULT_BARRIER_TTL_MS;
  let resolvedIsNewer:
    | ((cached: unknown, incoming: unknown) => boolean)
    | undefined = isCacheNewer;

  if (typeof setKeyOrOptions === 'function') {
    resolvedSetKey = setKeyOrOptions;
    resolvedDeleteKeys = deleteKeysFn ?? null;
    resolvedInvalidateKeys = invalidateKeysFn ?? null;
    resolvedIsNewer = isCacheNewer;
  } else if (setKeyOrOptions && typeof setKeyOrOptions === 'object') {
    resolvedSetKey = setKeyOrOptions.setKey ?? null;
    resolvedDeleteKeys = setKeyOrOptions.deleteKeys ?? null;
    resolvedInvalidateKeys = setKeyOrOptions.invalidateKeys ?? null;
    resolvedTtl = setKeyOrOptions.ttl;
    resolvedBarrierTtl = setKeyOrOptions.barrierTtl ?? DEFAULT_BARRIER_TTL_MS;
    resolvedIsNewer =
      setKeyOrOptions.isNewer === null
        ? undefined
        : (setKeyOrOptions.isNewer ?? isCacheNewer);
  } else if (setKeyOrOptions === null) {
    resolvedSetKey = null;
    resolvedDeleteKeys = deleteKeysFn ?? null;
    resolvedInvalidateKeys = invalidateKeysFn ?? null;
    resolvedIsNewer = isCacheNewer;
  } else {
    throw new Error(
      '@Cache decorator requires an explicit key derivation function or options object.',
    );
  }

  if (!resolvedSetKey && !resolvedDeleteKeys && !resolvedInvalidateKeys) {
    throw new Error(
      '@Cache decorator requires at least one of setKey, deleteKeys, or invalidateKeys to be specified.',
    );
  }

  return (
    _target: object,
    _propertyKey: string | symbol,
    descriptor: PropertyDescriptor,
  ) => {
    const original = descriptor.value as (
      entity: TEntity,
    ) => Promise<TResult | null>;

    descriptor.value = async function (
      this: CommandRepository<TEntity, unknown | null>,
      entity: TEntity,
    ): Promise<TResult | null> {
      const result = await original.call(this, entity);

      if (!this.cache) {
        return result;
      }

      // Cache maintenance is best-effort: the DB write already succeeded,
      // so a cache failure must not turn a success into an error (which
      // would cause idempotency release-on-error to drop the claim).
      try {
        if (result === null || result === undefined) {
          if (resolvedDeleteKeys) {
            let deleteKeys: string[] = [];
            try {
              deleteKeys = resolvedDeleteKeys(entity) ?? [];
            } catch (err) {
              logger.warn(
                `Failed resolving deleteKeys during cache eviction: ${err instanceof Error ? err.message : String(err)}`,
              );
            }
            for (const key of deleteKeys) {
              try {
                const barrier = createCacheMutationBarrier('deleted', entity);
                await this.cache.set(key, barrier as never, {
                  ttl: resolvedBarrierTtl,
                });
              } catch (err) {
                logger.warn(
                  `Failed installing deletion barrier for key "${key}": ${err instanceof Error ? err.message : String(err)}`,
                );
              }
            }
          }
          return result;
        }

        if (resolvedInvalidateKeys) {
          let invalidateKeys: string[] = [];
          try {
            invalidateKeys = resolvedInvalidateKeys(entity) ?? [];
          } catch (err) {
            logger.warn(
              `Failed resolving invalidateKeys during cache maintenance: ${err instanceof Error ? err.message : String(err)}`,
            );
          }
          for (const key of invalidateKeys) {
            try {
              const barrier = createCacheMutationBarrier('invalidated', entity);
              await this.cache.set(key, barrier as never, {
                ttl: resolvedBarrierTtl,
              });
            } catch (err) {
              logger.warn(
                `Failed installing invalidation barrier for key "${key}": ${err instanceof Error ? err.message : String(err)}`,
              );
            }
          }
        }

        if (resolvedSetKey) {
          let setKey: string | undefined;
          try {
            setKey = resolvedSetKey(entity);
          } catch (err) {
            logger.warn(
              `Failed resolving setKey during cache maintenance: ${err instanceof Error ? err.message : String(err)}`,
            );
          }
          if (setKey) {
            try {
              const snapshot = toCacheSnapshot(result);
              const setOptions = {
                ttl: resolvedTtl,
                isNewer: resolvedIsNewer,
              };
              await this.cache.set(setKey, snapshot, setOptions);
            } catch (err) {
              logger.warn(
                `Failed setting cache key "${setKey}": ${err instanceof Error ? err.message : String(err)}`,
              );
            }
          }
        }
      } catch (err) {
        logger.warn(
          `Unexpected error during cache maintenance: ${err instanceof Error ? err.message : String(err)}`,
        );
      }

      return result;
    };
  };
}
